### ISSUE TITLE
Tracking Lesson progress

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko-webapp#18]
DOD
- [x] Lesson Progression schema(Lesson History)
collect learner's lesson progress, section progress, total earn exp/coin including completed quiz card result
- [x] Quiz card Completion schema
collect, validate learner's completed card, and allow learner to earn exp/coin from card
- [x] Completion and Progression function Implementation

*Applying Lesson progress data
allow learner to continue working on the left lesson's content

**Comment by kithe-raker** [comment]
I have already create function to create a recap of the quiz, but haven't yet implement the coin/exp earning sytem

**Comment by kithe-raker** [comment]
@athensclub There is a part of applying progress data of previous session to the lesson, which has not been implement yet. So I want you to help me finish that task

**Comment by kithe-raker** [comment]
After I finished working on the dashboard's data, I will comeback and finish the `Completion and Progression function Implementation`

**Comment by kithe-raker** [comment]
Time is running out, so I will postpone the `Applying Lesson progress data` task for now
